using OblivionUI;
using System.Globalization;

int checks=0;
void Check(bool value) { if (!value) throw new Exception($"Check {checks+1} failed"); checks++; }
void Throws(Action action) { try { action(); } catch (ArgumentException) { checks++; return; } throw new Exception("Expected rejected input"); }
var q=new NotificationQueue();
q.Add("Left", "Body",NotificationSide.Left,1);
Check(q.Frame(0).Left=="@oui|-380.0|Left|Body");
Check(q.Frame(.16).Left=="@oui|-190.0|Left|Body");
Check(q.Frame(.32).Left=="@oui|-0.0|Left|Body" || q.Frame(.32).Left=="@oui|0.0|Left|Body");
Check(q.Frame(1).Right=="");
Check(q.Frame(1.48).Left=="@oui|-190.0|Left|Body");
Check(q.Frame(1.65)==("",""));
var cancel=q.Add("Cancelled","",NotificationSide.Right,2); cancel.Dispose();
q.Add("Right","",NotificationSide.Right,1);
Check(q.Frame(2).Right=="@oui|380.0|Right|");
q.Clear(); Check(q.Frame(3)==("",""));
for (int i=0;i<20;i++) q.Add(i.ToString(),"",NotificationSide.Left,1);
Check(q.Frame(4).Left.Contains("|4|"));
q.Clear(); var active=q.Add("Active","",NotificationSide.Right,1); q.Frame(5); active.Dispose(); Check(q.Frame(5.1)==("",""));
Throws(()=>Notifications.Show("x",duration:double.NaN));
Throws(()=>Notifications.Show("x",duration:.5));
Throws(()=>Notifications.Show("x",duration:31));
Throws(()=>Notifications.Show("x",side:(NotificationSide)99));
Hud.SetPrompt("[F2] Open store");
Notifications.Show("Title|injected", "body\nline",NotificationSide.Right);
var packet=Hud.Queue.Frame(0).Right;
Check(packet=="@oui|380.0|Title injected|body line");
Check(Hud.Prompt=="[F2] Open store");
Hud.SetPrompt(null); Check(Hud.Queue.Frame(.4).Right!="");
Notifications.Clear(); Check(Hud.Queue.Frame(.5)==("",""));
CultureInfo.CurrentCulture=CultureInfo.GetCultureInfo("de-DE");
Notifications.Show("Number","",NotificationSide.Right);
Check(Hud.Queue.Frame(1).Right.StartsWith("@oui|380.0|"));
Hud.Reset(); Notifications.Show(new string('x',500),new string('y',500));
var parts=Hud.Queue.Frame(2).Right.Split('|'); Check(parts[2].Length==64 && parts[3].Length==180);
Hud.Reset(); Check(Hud.Prompt=="" && Hud.Queue.Frame(3)==("",""));
Throws(()=>Books.Open(new()));
Throws(()=>Books.Open(new(){Pages=[new(){Elements=[new(){Id="same"},new(){Id="same"}]}]}));
Throws(()=>Books.Open(new(){Pages=[new(){Elements=[new(){Id="s",Kind=BookControl.Slider,Minimum=5,Maximum=2}]}]}));
Throws(()=>Books.Open(new(){Pages=[new(){Elements=[new(){Id="d",Kind=BookControl.Dropdown,Options=["A"],SelectedIndex=1}]}]}));
var options=new[]{"A","B"};
var book=Books.Open(new(){Pages=[new(){Elements=[new(){Id="d",Kind=BookControl.Dropdown,Options=options}]},new()]});
options[0]="Changed outside"; Check(book.Definition.Pages[0].Elements[0].Options[0]=="A");
book.GoToPage(1); Check(book.Page==1); Throws(()=>book.GoToPage(2));
book.Update("d",x=>x with {SelectedIndex=1}); Check(book.Definition.Pages[0].Elements[0].SelectedIndex==1);
Throws(()=>book.Update("d",x=>x with {Id="renamed"}));
Check(book.Definition.Pages[0].Elements[0].Id=="d");
var replacement=Books.Open(new(){Pages=[new()]}); Check(!book.IsOpen && replacement.IsOpen); replacement.Dispose(); Check(!replacement.IsOpen);
Throws(()=>Books.Open(new(){Title=null!,Pages=[new()]}));
Throws(()=>Books.Open(new(){Pages=[new(){Elements=[new(){Id="null-text",Text=null!}]}]}));
Throws(()=>Books.Open(new(){Pages=[new(){Elements=[new(){Id="overflow",Kind=BookControl.Slider,Maximum=double.MaxValue}]}]}));
Throws(()=>Books.Open(new(){Pages=[new(){Elements=[new(){Id="underflow",Kind=BookControl.Slider,Step=double.Epsilon}]}]}));
Console.WriteLine($"All {checks} notification and book API checks passed.");
